{% set name = "ase-db-backends" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ase_db_backends-{{ version }}.tar.gz
  sha256: f5a53caf178039aaf6e50bf3f6f35d8b73283a30674e7a49afcb29ce3c0b423f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - ase
    - numpy
    - psycopg2-binary
    - pymysql
    - cryptography

test:
  imports:
    - ase_db_backends
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/ase/ase-db-backends
  summary: ASE-DB backends
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
